/*
  ==============================================================================

    MusicTrack.h
    Created: 20 Aug 2021 8:58:44am
    Author:  Alana Schroeder

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>

class MusicTrack
{
public:
    /** 
     * Constructor 
     *
     * @param _trackID   - The unique ID of the track. This is generated by 
     *                     the library.
     * @param _fileName  - The name of the audio file for the track.
     * @param _audioURL  - A JUCE URL for the audio file of the track.
     * @param _length    - A formatted string containing the track length.
     */
    MusicTrack(int _trackID, 
               juce::String _fileName, 
               juce::URL _audioURL, 
               std::string _length);


    int trackID;                // the unique track ID
    juce::String fileName;      // the track title
    juce::URL audioURL;         // the track file URL
    std::string length;         // the track length
};